"""Add student_code to Student table

Revision ID: 98de2445b0d4
Revises: 
Create Date: 2024-01-05 15:26:08.883012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '98de2445b0d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER SEQUENCE student_id_seq RESTART WITH 1 INCREMENT BY 1;"))
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_code', sa.String(length=10), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('major',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('major',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('student_code')

    # ### end Alembic commands ###
